stages:
  - test
  - build
  - deploy
default:
  image: node:lts
  tags:
    - node
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .npm/

.install:
  before_script:
    - npm ci --cache .npm --prefer-offline

test:
  stage: test
  before_script:
    - apt-get -q update
    - wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apt install -y ./google-chrome*.deb > /dev/null;
    - export CHROME_BIN=/usr/bin/google-chrome
    - !reference [.install, before_script]
  script:
    - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

build-pages:
  stage: build
  extends: .install
  artifacts:
    paths:
      - dist/posterize
  script:
    - npm run build -- --base-href /$CI_PROJECT_NAME/

pages:
  stage: deploy
  needs: [build-pages]
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - ls -alF
    - echo $CI_PAGES_URL
    - echo $CI_PROJECT_NAME
    - mv dist/posterize public
  artifacts:
    paths:
      - public
