stages:
  - test
  - build
  - deploy
default:
  image: node:lts
  tags:
    - node
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline

.install:
  before_script:
    - npm ci --cache .npm --prefer-offline

test:
  stage: test
  before_script:
    - apt-get -q update
    - wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apt-get -qq install -qq -y ./google-chrome*.deb;
    - export CHROME_BIN=/usr/bin/google-chrome
    - !reference [.install, before_script]
  script:
    - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
